<meta charset="utf-8" />
  <meta name="description" content="Internet access plan" />
  <meta name="keywords" content="Internet services,Broadband connection" />
  <meta name="author" content="Ishika"  />
  <link href="styles/style.css" rel="stylesheet"/>
  <!-- Load font awesome icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 