  <!--Navigation bar of main menu-->
  <nav>
      <ul class="navbar">
        <li><a href="index.php">Home</a> </li>
        <li><a href="product.php">Plans Available</a> </li>
        <li><a href="about.php">About Us</a></li>
        <li><a href="enquire.php">Contact us</a> </li>
        <li><a href="payment.php">Payment</a></li>
        <li><a href="enhancements.php">Enhancements</a> </li>
        <li><a href="enhancements2.php">Enhancements 2</a> </li>
      </ul>
    </nav>
    <hr />